#ifndef TESTATAUFGABE_FELIXFRASCH_1_0_CONFIG_H
#define TESTATAUFGABE_FELIXFRASCH_1_0_CONFIG_H

#define FLENGTH   100
#define ALENGTH   100
#define DATEINAME "Karteikarten.csv"

#endif //TESTATAUFGABE_FELIXFRASCH_1_0_CONFIG_H